name: Deploy Vue App - GitHub-Pages Branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Vue App Build
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout branch master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Use Node.js v14.15.1
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.1'

    - name: npm install
      run: |
        npm install

    - name: npm install
      run: |
        npm run build

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  deploy_prod:
    name: Deploy App - GitHub-Pages Branch
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch GitHub-Pages
      uses: actions/checkout@v2
      with:
        ref: GitHub-Pages

    - name: Set global git username/email
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./

    - run: git add --all && git commit -m "Deploy $(TZ=":America/Sao_Paulo" date +"%d-%m-%Y %T")"
    - run: git push origin GitHub-Pages